/* Auto-generated by tests/mine-puzzles.js — every puzzle engine-verified:
   forced mate in N with a UNIQUE first move. Do not edit by hand. */
(function () {
  'use strict';
  var PUZZLES = [
  {
    "id": "p1",
    "fen": "rn6/p6r/3k3p/1b1ppp2/2p1Pnp1/6P1/1RPq2BK/3N3R b - - 3 42",
    "mateIn": 1,
    "best": "d2g2",
    "pv": [
      "d2g2"
    ]
  },
  {
    "id": "p2",
    "fen": "r7/2k1n3/2b5/1pP2p2/1P1n1p1R/2b5/5B1P/2K5 b - - 3 48",
    "mateIn": 1,
    "best": "a8a1",
    "pv": [
      "a8a1"
    ]
  },
  {
    "id": "p3",
    "fen": "4k2r/3r4/p1pqp1p1/1pb2n2/PPp2P1p/1R3PP1/3PNnBR/BQK5 b - - 5 34",
    "mateIn": 1,
    "best": "d6d2",
    "pv": [
      "d6d2"
    ]
  },
  {
    "id": "p4",
    "fen": "r1bqkbnr/pp1pp3/n4p2/2p3pp/8/1PP1P3/P1QPKPPP/RNB2BNR w kq - 0 6",
    "mateIn": 1,
    "best": "c2g6",
    "pv": [
      "c2g6"
    ]
  },
  {
    "id": "p5",
    "fen": "r1bqkb2/ppppp2Q/8/5pP1/3P4/3n2Pr/PPP1P2P/RNB2KNr w q - 5 15",
    "mateIn": 1,
    "best": "h7g6",
    "pv": [
      "h7g6"
    ]
  },
  {
    "id": "p6",
    "fen": "1rbqkb2/1p1pp3/2p5/p2P2P1/8/3Q2Pr/PnP1P2P/RNB2KNr w - - 0 19",
    "mateIn": 1,
    "best": "d3g6",
    "pv": [
      "d3g6"
    ]
  },
  {
    "id": "p7",
    "fen": "1nb2b2/2qpk1nr/P5p1/1p4NP/3P4/1ppK3N/1P2rP1P/2R4R b - - 0 26",
    "mateIn": 1,
    "best": "c7c4",
    "pv": [
      "c7c4"
    ]
  },
  {
    "id": "p8",
    "fen": "r4k1r/ppp2p2/3n1q1n/6pp/2Q5/2P1p3/PB1P2bP/2RBK1NR b - - 3 26",
    "mateIn": 1,
    "best": "f6f2",
    "pv": [
      "f6f2"
    ]
  },
  {
    "id": "p9",
    "fen": "1nb1k1r1/rpp3b1/4p1p1/pP1q3p/1QPPp1n1/B3p1P1/P3BP1P/RN1K3R w - - 4 19",
    "mateIn": 1,
    "best": "b4e7",
    "pv": [
      "b4e7"
    ]
  },
  {
    "id": "p10",
    "fen": "4qkr1/p5b1/b4p1p/1p1p2P1/3p1PP1/1N1KP3/RPr5/2B3NR b - - 4 33",
    "mateIn": 1,
    "best": "e8e4",
    "pv": [
      "e8e4"
    ]
  },
  {
    "id": "p11",
    "fen": "1B1k2nr/1p1P1ppb/2p5/2b4P/2PP4/1P4n1/r4P1P/R3K1NR b - - 0 24",
    "mateIn": 2,
    "best": "c5b4",
    "pv": [
      "c5b4",
      "e1d1",
      "a2a1"
    ]
  },
  {
    "id": "p12",
    "fen": "4k2r/r5p1/p1p1p3/1pbpnn1p/PP3P1q/1RP2bP1/3PP1BR/B2QK1N1 b - - 1 26",
    "mateIn": 2,
    "best": "h4g3",
    "pv": [
      "h4g3",
      "e1f1",
      "g3f2"
    ]
  },
  {
    "id": "p13",
    "fen": "r1b1k3/p1B2ppr/np6/3pp1qp/Pb1Pn3/N3Q1P1/RPP1P2P/3K1B1R b q - 3 15",
    "mateIn": 2,
    "best": "g5e3",
    "pv": [
      "g5e3",
      "c7e5",
      "e3d2"
    ]
  },
  {
    "id": "p14",
    "fen": "r1bqk1n1/ppppp1b1/2n5/5pPr/2QP4/6P1/PPP1P1pP/RNBK2NR w q - 0 10",
    "mateIn": 2,
    "best": "c4g8",
    "pv": [
      "c4g8",
      "g7f8",
      "g8g6"
    ]
  },
  {
    "id": "p15",
    "fen": "1rb1kb2/1pqpp3/3P4/p5P1/2p3Q1/6r1/PnP1P2P/RNB2KNr b - - 1 23",
    "mateIn": 2,
    "best": "h1g1",
    "pv": [
      "h1g1",
      "f1f2",
      "b2d1"
    ]
  },
  {
    "id": "p16",
    "fen": "6n1/1r2B2p/4k3/p5p1/Pp2P1q1/1P1P4/2K3p1/8 b - - 0 38",
    "mateIn": 2,
    "best": "g4e2",
    "pv": [
      "g4e2",
      "c2b1",
      "g2g1q"
    ]
  },
  {
    "id": "p17",
    "fen": "2k5/1r6/4P3/p5pp/Pp4q1/1PBP4/2K5/6q1 b - - 1 43",
    "mateIn": 2,
    "best": "g4d1",
    "pv": [
      "g4d1",
      "c2b2",
      "d1b1"
    ]
  },
  {
    "id": "p18",
    "fen": "2rr4/pp3pk1/3n4/2pq2pp/PQ4n1/2PPp2b/1B5P/R2BK2R b - - 3 34",
    "mateIn": 2,
    "best": "d5h1",
    "pv": [
      "d5h1",
      "e1e2",
      "h1f1"
    ]
  },
  {
    "id": "p19",
    "fen": "7k/p4Q2/3r1p2/2p3p1/P1P3Bp/4p2q/1B5P/1R2Kb1R w - - 0 46",
    "mateIn": 2,
    "best": "b2f6",
    "pv": [
      "b2f6",
      "d6f6",
      "b1b8"
    ]
  },
  {
    "id": "p20",
    "fen": "1r2k2r/3q2bp/Q1B1Pp1n/p5p1/P5P1/1PP1KP1P/1q6/6NR b k - 2 31",
    "mateIn": 2,
    "best": "b2d2",
    "pv": [
      "b2d2",
      "e3e4",
      "d2f4"
    ]
  },
  {
    "id": "p21",
    "fen": "rn2Q1nq/Nb5k/6R1/2p2P1p/1p2Pp2/2P5/PB1P1K1P/RN3B2 w - - 0 30",
    "mateIn": 2,
    "best": "e8f7",
    "pv": [
      "e8f7",
      "h8g7",
      "f7g7"
    ]
  },
  {
    "id": "p22",
    "fen": "2b5/r7/3k4/p2ppp2/P2P2p1/2P1KNPN/4PP2/bqR2B2 b - - 5 32",
    "mateIn": 2,
    "best": "b1c1",
    "pv": [
      "b1c1",
      "f3d2",
      "c1c3"
    ]
  },
  {
    "id": "p23",
    "fen": "b1Q2qkr/r3p1b1/pp4P1/3PPp1p/4PP2/BP3K2/6PR/RN3BN1 w - - 1 27",
    "mateIn": 2,
    "best": "c8e6",
    "pv": [
      "c8e6",
      "f8f7",
      "e6f7"
    ]
  },
  {
    "id": "p24",
    "fen": "b5k1/1r4b1/pp1Q2Pr/3PP2p/4pP2/BP4P1/4BK1R/RN4N1 w - - 1 34",
    "mateIn": 2,
    "best": "d6d8",
    "pv": [
      "d6d8",
      "g7f8",
      "d8f8"
    ]
  },
  {
    "id": "p25",
    "fen": "1B6/1R6/5k1p/1bppp1pP/4PpP1/1PKP4/2PNP3/1R1Q1BN1 w - - 1 34",
    "mateIn": 3,
    "best": "e4d5",
    "pv": [
      "e4d5",
      "b5d3",
      "c2d3",
      "c5c4",
      "d2e4"
    ]
  },
  {
    "id": "p26",
    "fen": "1B6/8/5k1p/4p1pP/2R1B1P1/1P3p2/1KPN4/1R5N w - - 5 47",
    "mateIn": 3,
    "best": "c4c7",
    "pv": [
      "c4c7",
      "f3f2",
      "e4d5",
      "f2f1q",
      "b1f1"
    ]
  },
  {
    "id": "p27",
    "fen": "3k4/2r1n2Q/b2pP2P/1n5p/p2p4/P1N1P3/4NPB1/R1BK3R w - - 1 28",
    "mateIn": 3,
    "best": "h7h8",
    "pv": [
      "h7h8",
      "e7g8",
      "h8g8",
      "d8e7",
      "c3d5"
    ]
  },
  {
    "id": "p28",
    "fen": "1R6/nb2Q3/1krpP2P/7p/p7/P1p1P3/2K1NP2/R1B5 w - - 3 36",
    "mateIn": 3,
    "best": "e7b7",
    "pv": [
      "e7b7",
      "b6c5",
      "e2c3",
      "c5c4",
      "b7b4"
    ]
  },
  {
    "id": "p29",
    "fen": "N3Q3/1R6/2npP2P/k1r5/p6p/P1p1P3/2K2P2/R1B5 w - - 0 42",
    "mateIn": 3,
    "best": "a8c7",
    "pv": [
      "a8c7",
      "c6a7",
      "e8a8",
      "c5c7",
      "a8a7"
    ]
  },
  {
    "id": "p30",
    "fen": "r5n1/6kp/2n5/p5p1/Pp1P2Pq/1P1PP1p1/3K4/8 b - - 0 31",
    "mateIn": 3,
    "best": "g3g2",
    "pv": [
      "g3g2",
      "d4d5",
      "h4f2",
      "d2c1",
      "g2g1q"
    ]
  },
  {
    "id": "p31",
    "fen": "8/3n3k/2NR1P2/2p1P2p/1PBq1p2/3b1K2/r2P3P/RNB5 b - - 0 44",
    "mateIn": 3,
    "best": "d4e4",
    "pv": [
      "d4e4",
      "f3f2",
      "e4e2",
      "f2g1",
      "e2f1"
    ]
  },
  {
    "id": "p32",
    "fen": "r1bq4/p1p2Q2/3k4/3ppp2/P2P2p1/2P2NP1/1b2PP2/2R1KBNR w - - 1 23",
    "mateIn": 3,
    "best": "h1h6",
    "pv": [
      "h1h6",
      "d8f6",
      "h6f6",
      "c8e6",
      "f6e6"
    ]
  },
  {
    "id": "p33",
    "fen": "r2qkb1r/pb2pp1p/n3Q3/1ppp2p1/P3n2P/2PBP3/1P1P1PP1/RNB1K1NR w KQkq - 1 10",
    "mateIn": 3,
    "best": "d3b5",
    "pv": [
      "d3b5",
      "b7c6",
      "b5c6",
      "d8d7",
      "e6d7"
    ]
  },
  {
    "id": "p34",
    "fen": "b5k1/1rb5/Q5Pr/1p1P4/2B1pPp1/BP6/7R/RN3KN1 w - - 2 38",
    "mateIn": 3,
    "best": "a6e6",
    "pv": [
      "a6e6",
      "g8g7",
      "e6f7",
      "g7h8",
      "h2h6"
    ]
  }
];
  if (typeof module !== 'undefined' && module.exports) module.exports = PUZZLES;
  else (typeof window !== 'undefined' ? window : this).RTG_PUZZLES = PUZZLES;
}());
